ckanext/who_romania/auth.py
from ckan.plugins import toolkit


def lambda_invoke(context, data_dict):
    authorized_users = toolkit.config.get('ckanext.who_romania.lambda_invoke_users', " ")
    authorized_users = authorized_users.split(" ")
    if context['user'] in authorized_users:
        return {'success': True}
    else:
        return {
            'success': False,
            'msg': 'You are not authorized to carry out this action'
        }

ckanext/who_romania/blueprints.py
import logging
from flask import Blueprint, request
from ckan.plugins import toolkit
from datetime import datetime

log = logging.getLogger(__name__)
lambda_blueprint = Blueprint(
    'lambda',
    __name__,
    url_prefix="/lambda/"
)


def view_logs(lambda_function, logs=None):
    try:
        toolkit.check_access('lambda_invoke', {})
    except toolkit.NotAuthorized:
        toolkit.abort(403, toolkit._('Not authorized to perform this action'))
    if logs is None:
        try:
            logs = toolkit.get_action('lambda_logs')({}, {
                'lambda_function': lambda_function
            })['events']
        except Exception as e:
            logs = [
                {'message': f"[ERROR]\t{datetime.now()}\twrc\tERROR Failed to get logs"},
                {'message': f"[ERROR]\t{datetime.now()}\twrc\t{type(e).__name__}: {e}"}
            ]
    if logs == []:
        logs = [
            {'message': f"[INFO]\t{datetime.now()}\twrc\tNothing logged yet, please "
                        "wait a moment and then reload the page"},
        ]
    extra_vars = {
        "logs": logs,
        "lambda_function": lambda_function
    }
    return toolkit.render(
        'who_romania/lambda_logs.html', extra_vars
    )


def family_medicine(dataset_id):
    try:
        toolkit.check_access('package_update', {}, {'id': dataset_id})
        toolkit.check_access('lambda_invoke', {})
    except toolkit.NotAuthorized:
        toolkit.abort(403, toolkit._('Not authorized to perform this action'))

    lambda_function = toolkit.config.get(
        'ckanext.who_romania.lambda_family_medicine_function',
        ''
    )
    if request.method == 'POST':
        reporting_template = toolkit.config.get(
            'ckanext.who_romania.lambda_family_medicine_template',
            ''
        )
        data_dict = {
            'dataset_id': dataset_id,
            'lambda_function': lambda_function,
            'reporting_template': reporting_template
        }
        try:
            toolkit.get_action('lambda_invoke')({}, data_dict)
            toolkit.h.flash_success(toolkit._(
                "Sucessfully triggered aggregation script. The script will take no "
                "more than 5 minutes to complete.  Follow the logs below..."
            ))
        except Exception as e:
            toolkit.h.flash_error(toolkit._(
                "Failed to trigger aggregation script. Please try again and if the "
                f"problem persists, contact a system administrator ({e}). "
            ))

    return toolkit.redirect_to(
        'lambda.view_logs',
        lambda_function=lambda_function,
        logs=[]
    )


lambda_blueprint.add_url_rule(
    '/logs/<lambda_function>',
    view_func=view_logs
)

lambda_blueprint.add_url_rule(
    '/family-medicine/<dataset_id>',
    view_func=family_medicine,
    methods=['POST', 'GET']
)

ckanext/who_romania/templates/base.html
{% ckan_extends %}

{% block styles %}
    {{ super() }}
    {% block fjelltopp_theme_palette %}{% asset 'who-romania/wrc-theme-palette' %}{% endblock %}
    {% block fjelltopp_theme_extended %}{% endblock %}
    {% asset 'who-romania/who-romania-theme' %}
{% endblock %}

ckanext/who_romania/templates/footer.html
{% ckan_extends %}

{% block footer_nav %}
    {% snippet 'snippets/footer_links.html', copyrights_owner='<a href="https://www.who.int/romania" target="_blank">WHO Romania Country Office</a>' | safe, devs='<a class="hide-text" target="_blank" href="https://fjelltopp.org">Fjelltopp</a>' %}
{% endblock %}

{% block footer_logo_section %}
<a href="https://who.int" target="_blank"><img class="footer-logo" src="/images/who.png" alt=""/></a>
{% endblock %}

ckanext/who_romania/templates/group/snippets/package_group_item.html
{% extends 'group/snippets/group_item.html' %}

{% block item %}

    <div class="col-lg-4 col-md-6 col-xs-12">
        <div class="category-box">
            <img src="{{ group.image_display_url or h.url_for_static('/base/images/placeholder-group.png') }}" alt="{{ group.name }}" class="media-image group-thumbnail">
            <div class="group-text">
                <div class="title">
                    <a href="{{ url }}">{{ group.title }}</a>
                </div>
                {% if group.package_count %}
                  <div class="desc">{{ ungettext('{num} Dataset', '{num} Datasets', group.package_count).format(num=group.package_count) }}</div>
                {% endif %}
                {% if group.user_member %}
                    <button name="group_remove.{{ group.id }}"
                            type="submit"
                            class="btn btn-delete btn-sm media-edit"
                            title="{{_('Remove dataset from this category')}}">
                      <i class="fa fa-remove"> </i>
                    </button>
                {% endif %}
            </div>
        </div>
    </div>

{% endblock %}

ckanext/who_romania/templates/group/snippets/package_group_list.html
{% extends 'group/snippets/group_list.html' %}

{% block group_list %}
    {% set groups = groups %}
        <ul class="topics">
        {% for group in groups %}
            {% snippet "group/snippets/package_group_item.html", group=group, position=loop.index %}
        {% endfor %}
        </ul>
{% endblock %}

ckanext/who_romania/templates/header.html
{% ckan_extends %}


{% block header_logo %}
    {% snippet 'snippets/header_logo.html',
        site_title = g.site_title,
        logo='/images/logo.png',
        header_title='Data & Documentation Library<br/>WHO Romania Country Office' | safe %}
{% endblock %}

{% block nav_items_signed %}
    {{ h.build_nav_main(
        ('dataset.search', _('Datasets')),
        ('group.index', _('Categories')),
        ('user.index', _('Users'))
         ) }}
{% endblock %}

{% block nav_items_unsigned %}
    {{ h.build_nav_main(
        ('dataset.search', _('Datasets')),
        ('group.index', _('Categories')),
        ('user.index', _('Users')),
        (h.get_login_view(), _('Log in'))
         ) }}
{% endblock %}

ckanext/who_romania/templates/home/layout1.html
{% ckan_extends %}

{% block fx_bg %}{% endblock %}

{% block title %}{{ _('Featured data') }}{% endblock %}
{% block first_row_title %}{{ _('Featured datasets') }}{% endblock %}
{% block second_row_title %}{{ _('Recently updated datasets') }}{% endblock %}

ckanext/who_romania/templates/home/snippets/about_text.html
<div>
    <h3><strong>WHO Romania Data and Documentation Library</strong><span> was established to create a unified space where research and evaluation outputs can be easily accessed, shared, and utilized by a broad range of stakeholders.
    <div class="contact">
        <p>Thank you for visiting the repository. Your engagement is critical to our success. For more information or to contribute to the repository, please contact us.</p>
    </div>
</div>

ckanext/who_romania/templates/home/snippets/insights.html
{% ckan_extends %}

{% block top_container_title %}{% endblock %}
{% block top_container %}{% endblock %}
{% block bottom_container %}{% endblock %}

ckanext/who_romania/templates/home/snippets/promoted.html
{% set tags = h.get_facet_items_dict('tags', c.search_facets, limit=3) %}
{% set placeholder = _('E.g. environment') %}
{% set stats = h.get_site_statistics() %}

{% block promote %}
<div class="promoted promoted-home col-xs-12 col-sm-12 col-lg-12" >
    <div class="promoted-container row">

            <div class="promoted-text">
                <p class="subtitle">{{_('WHO Romania Country Office')}}</p>
                <h1 class="headline">{{_('Data & Documentation Library')}}</h1>
                <p class="description">
                    {{_('A platform for the WHO Romania Country Office to archive datasets and documentation for dissemination across internal and external partners.')}}
                </p>
            </div>

            <div class="search-section">
            <h2>{{ _('Search {0} datasets:').format(h.SI_number_span(stats.dataset_count)) }}</h2>
            {% snippet 'snippets/search_input.html', placeholder='e.g environment' %}
            <p class="show-categories">{{_('Or')}} <a class="small" href="{{ h.url_for('/group/') }}">{{_('find data by category')}}</a></p>
            </div>
    </div>
</div>
{% endblock %}

ckanext/who_romania/templates/package/edit_base.html
{% ckan_extends %}

{% block secondary_content %}
  {{super()}}
  {% if pkg['type'] in ['family-medicine'] and h.check_access('lambda_invoke')%}
    <section class="module module-narrow automation">
      <div class="module context-info">
        <div class="module-content">
            <p>{{_('Automation is available to create a monthly aggregated dataset from this data...')}}</p>
            <form action="{{h.url_for('lambda.family_medicine', dataset_id=pkg['id'])}}" method="post">
              <input type="submit" class="btn btn-primary" value="{{_('Aggregate Now')}}" />
            </form>
        </div>
      </div>
    </section>
  {% endif %}
{% endblock %}

ckanext/who_romania/templates/package/new_resource.html
{% ckan_extends %}

{% block form %}{% snippet resource_form_snippet, data=data, errors=errors, error_summary=error_summary, include_metadata=false, pkg_name=pkg_name, stage=stage, dataset_type=dataset_type %}{% endblock %}

ckanext/who_romania/templates/package/resource_read.html
{% ckan_extends %}
{% block secondary_content %}
  {% block resources_list %}
    {% snippet "package/snippets/resources.html", pkg=pkg, active=res.id, action='read', is_activity_archive=is_activity_archive %}
  {% endblock %}

{# metadata as json #}
<div class="api-link pull-right small">
  <a target="_blank"
     href="{{h.url_for('api.action', ver=3, logic_function='resource_show', id=resource['id'])}}">
    {{_('View metadata as JSON')}}
  </a>
</div>
{% endblock %}

ckanext/who_romania/templates/package/snippets/resource_form.html
{% ckan_extends %}

{% set dataset = h.get_dataset_from_id(pkg_name) %}

{% block basic_fields_url %}
    {% asset 'who-romania/FileInputComponentStyles' %}
    <div
        id="FileInputComponent"
        data-lfsServer="{{ h.blob_storage_server_url() }}"
        data-maxResourceSize="{{ h.max_resource_size() }}"
        data-orgId="{{ dataset.organization.name }}"
        data-datasetName="{{ dataset.name }}"
        data-existingUrlType="{{ data.url_type if data else '' }}"
        data-existingUrl="{{ data.url if data else '' }}"
        data-existingSha256="{{ data.sha256 if data else '' }}"
        data-existingFileName="{{ h.blob_storage_resource_filename(data) if data else '' }}"
        data-existingSize="{{ data.size if data else '' }}"
    >       
        {% if data.url %}
            {% if data.url_type == 'upload' %}
                <h3 class="text-muted">
                    <span><i class="fa fa-spinner fa-spin"></i> {{ _('Loading') }}</span>
                </h3>
                <input name="url" data-testid="url" type="hidden" value="{{ data.url }}">
                <input name="url_type" data-testid="url_type" type="hidden" value="{{ data.url_type }}">
                <input name="lfs_prefix" data-testid="lfs_prefix" type="hidden" value="{{ data.lfs_prefix }}">
                <input name="sha256" data-testid="sha256" type="hidden" value="{{ data.sha256 }}">
                <input name="size" data-testid="size" type="hidden" value="{{ data.size }}">
            {% else %}
                <div>
                    <label class="control-label">{{ _('URL')}}</label>
                    <div class="input-group field-url-input-group">
                        <input
                            type="text"
                            placeholder="{{ _('Loading') }}..."
                            class="form-control"
                        />
                        <span class="input-group-btn">
                            <button class="btn btn-danger" type="button">{{ _('Remove') }}</button>
                        </span>
                    </div>
                </div>
            {% endif %}
        {% else %}
            <div class="dropzone text-muted">
                <h3><i class="fa fa-spinner fa-spin"></i> {{ _('Loading') }}</h3>
            </div>
        {% endif %}
    </div>
    {% asset 'who-romania/FileInputComponentScripts' %}
{% endblock %}

ckanext/who_romania/templates/package/snippets/resource_item.html
{% ckan_extends %}

{% block resource_item_description %}
    {% if res.size is not none %}
    <p class="resource-detail file-size">{{h.localised_filesize(res.size)}} modified {{h.time_ago_from_timestamp(res.last_modified) }}</p>
    {% endif %}
    {{ super() }}
{% endblock %}

ckanext/who_romania/templates/page.html
{% ckan_extends %}

{% block fx_bg %}{% endblock %}

{% block footer %}
    <div class="big-footer {% if c.userobj %}connected{% endif %}">
    {% include "footer.html" %}
    </div>
{% endblock %}

ckanext/who_romania/templates/scheming/form_snippets/month.html
{% import 'macros/form.html' as form %}
{% call form.input(
    field.field_name,
    id='field-' + field.field_name,
    label=h.scheming_language_text(field.label),
    placeholder=h.scheming_language_text(field.form_placeholder),
    type='month',
    value=(data.get(field.field_name) or '').split()[0],
    error=errors[field.field_name],
    classes=field.classes if 'classes' in field else ['control-medium'],
    attrs=dict({"class": "form-control"}, **(field.get('form_attrs', {}))),
    is_required=h.scheming_field_required(field)
    )
%}
    {%- snippet 'scheming/form_snippets/help_text.html', field=field -%}
{% endcall %}

ckanext/who_romania/templates/scheming/form_snippets/no_input.html
{# Preset values require no form snippet since their input value is preset in the package schema and populated by the scheming validator called "autofill".#}

ckanext/who_romania/templates/scheming/form_snippets/organization.html
{% ckan_extends %}
{% block package_metadata_fields_visibility %}
{% endblock %}

ckanext/who_romania/templates/scheming/form_snippets/user.html
{% import 'macros/form.html' as form %}
{% set default_value = h.get_user_obj(field.get('user_field', "")) or field.get('default', '') %}
{% call form.input(
    field.field_name,
    id='field-' + field.field_name,
    label=h.scheming_language_text(field.label),
    placeholder=h.scheming_language_text(field.form_placeholder),
    value=data.get(field.field_name, default_value),
    error=errors[field.field_name],
    classes=field.classes if 'classes' in field else ['control-medium'],
    attrs=dict({"class": "form-control"}, **(field.get('form_attrs', {}))),
    is_required=h.scheming_field_required(field)
    )
%}
    {%- snippet 'scheming/form_snippets/help_text.html', field=field -%}
{% endcall %}

ckanext/who_romania/templates/scheming/form_snippets/week.html
{% import 'macros/form.html' as form %}

{%- set options=h.get_week_options(dataset['month']) -%}

{%- if data[field.field_name] -%}
  {%- set option_selected = data[field.field_name]|string -%}
{%- else -%}
  {%- set option_selected = None -%}
{%- endif -%}

{% call form.select(
    field.field_name,
    id='field-' + field.field_name,
    label=h.scheming_language_text(field.label),
    options=options,
    selected=option_selected,
    error=errors[field.field_name],
    classes=field.classes if 'classes' in field else ['control-medium'],
    attrs=dict({"class": "form-control"}, **(field.get('form_attrs', {}))),
    is_required=h.scheming_field_required(field)
    )
%}
    {%- snippet 'scheming/form_snippets/help_text.html', field=field -%}
{% endcall %}

ckanext/who_romania/templates/scheming/package/snippets/resource_form.html
{% ckan_extends %}

{% block basic_fields %}

  {% asset 'who-romania/FileInputComponentStyles' %}
  {% set dataset = h.get_dataset_from_id(pkg_name) %}
  <div
      id="FileInputComponent"
      data-lfsServer="{{ h.blob_storage_server_url() }}"
      data-maxResourceSize="{{ h.max_resource_size() }}"
      data-orgId="{{ dataset.organization.name }}"
      data-datasetName="{{ dataset.name }}"
      data-existingUrlType="{{ data.url_type if data else '' }}"
      data-existingUrl="{{ data.url if data else '' }}"
      data-existingSha256="{{ data.sha256 if data else '' }}"
      data-existingFileName="{{ h.blob_storage_resource_filename(data) if data else '' }}"
      data-existingSize="{{ data.size if data else '' }}"
  >
      {% if data.url %}
          {% if data.url_type == 'upload' %}
              <h3 class="text-muted">
                  <span><i class="fa fa-spinner fa-spin"></i> {{ _('Loading') }}</span>
              </h3>
              <input name="url" data-testid="url" type="hidden" value="{{ data.url }}">
              <input name="url_type" data-testid="url_type" type="hidden" value="{{ data.url_type }}">
              <input name="lfs_prefix" data-testid="lfs_prefix" type="hidden" value="{{ data.lfs_prefix }}">
              <input name="sha256" data-testid="sha256" type="hidden" value="{{ data.sha256 }}">
              <input name="size" data-testid="size" type="hidden" value="{{ data.size }}">
          {% else %}
              <div>
                  <label class="control-label">{{ _('URL')}}</label>
                  <div class="input-group field-url-input-group">
                      <input
                          type="text"
                          placeholder="{{ _('Loading') }}..."
                          class="form-control"
                      />
                      <span class="input-group-btn">
                          <button class="btn btn-danger" type="button">{{ _('Remove') }}</button>
                      </span>
                  </div>
              </div>
          {% endif %}
      {% else %}
          <div class="dropzone text-muted">
              <h3><i class="fa fa-spinner fa-spin"></i> {{ _('Loading') }}</h3>
          </div>
      {% endif %}
  </div>
  {% asset 'who-romania/FileInputComponentScripts' %}

    {%- if not dataset_type -%}
    <p>
    dataset_type not passed to template. your version of CKAN
    might not be compatible with ckanext-scheming
    </p>
  {%- endif -%}
  {%- set dataset = h.get_dataset_from_id(pkg_name, validate=True) -%}
  {%- set schema = h.scheming_get_dataset_schema(dataset_type) -%}
  {%- for field in schema.resource_fields -%}
    {%- if field.form_snippet is not none -%}
      {%- if field.field_name not in data %}
        {# Set the field default value before rendering but only if
        it doesn't already exist in data which would mean the form
        has been submitted. #}
        {% if field.default_jinja2 %}
          {% do data.__setitem__(
            field.field_name,
            h.scheming_render_from_string(field.default_jinja2)) %}
        {% elif field.default %}
          {% do data.__setitem__(field.field_name, field.default) %}
        {% endif %}
      {% endif -%}
      {%- snippet 'scheming/snippets/form_field.html',
        field=field,
        data=data,
        errors=errors,
        licenses=c.licenses,
        entity_type='dataset',
        object_type=dataset_type,
        dataset=dataset
      -%}
    {%- endif -%}
  {%- endfor -%}

{% endblock %}

ckanext/who_romania/templates/scheming/snippets/form_field.html
{#- master snippet for all scheming form fields -#}
{#- render the field the user requested, or use a default field -#}
{%- set form_snippet = field.form_snippet|default(
  'repeating_subfields.html' if field.repeating_subfields else 'text.html') -%}

{%- if '/' not in form_snippet -%}
  {%- set form_snippet = 'scheming/form_snippets/' + form_snippet -%}
{%- endif -%}

{%- snippet form_snippet,
  field=field,
  data=data,
  errors=errors,
  licenses=licenses,
  entity_type=entity_type,
  object_type=object_type,
  dataset=dataset
-%}

ckanext/who_romania/templates/who_romania/lambda_logs.html
{% extends "page.html" %}

{% block breadcrumb_content %}
    <li>{{_('Automation Logs')}}</li>
    <li class="active"><a href="">{{lambda_function}}</a></li>
{% endblock %}

{% block primary_content %}
  <section class="module">
    <div class="module-content">
      <h1 class="heading">Automation Logs</h1>
      <div class="logs">
        {% for event in logs %}
            {% set log = " ".join(event.message.split("\t")[3:]).strip() %}
            {% set type = event.message.split('\t')[0].lower()[1:-1] %}
            {% if log %}
                <p class="log {{type}}">{{log|urlize}}</p>
            {% endif %}
        {% endfor %}
      </div>
      <p class="logs-reload">{{_('<a href=""><i class="fa fa-sync"></i>Reload the page</a> to see latest logs...')}}
    </div>
  </section>
{% endblock %}

{% block secondary_content %}
    <section class="module module-narrow">
      <div class="module context-info">
        <div class="module-content">
          <h1 class="heading">Automation Logs</h1>
          <p class="small automation-function">
            <strong>{{_('For the latest invokation of:')}}</strong>
            <br/>{{lambda_function}}
          </p>
        </div>
      </div>
    </section>
{% endblock %}